### ISSUE TITLE
Does not work on 1.6.0

### ISSUE THREAD

**Issue by koblue** [bbc-mc/sdweb-merge-board#19]
Throws this error every time on 1.6.0

```
run_modelmerger() missing 3 required positional arguments: 'add_merge_recipe', 'copy_metadata_fields', and 'metadata_json'
Try to use old 'run_modelmerger' params.
run_modelmerger() missing 4 required positional arguments: 'save_metadata', 'add_merge_recipe', 'copy_metadata_fields', and 'metadata_json'
Try to use old 'run_modelmerger' params.
run_modelmerger() missing 5 required positional arguments: 'discard_weights', 'save_metadata', 'add_merge_recipe', 'copy_metadata_fields', and 'metadata_json'
Try to use old 'run_modelmerger' params.
run_modelmerger() missing 7 required positional arguments: 'config_source', 'bake_in_vae', 'discard_weights', 'save_metadata', 'add_merge_recipe', 'copy_metadata_fields', and 'metadata_json'
Try to use old 'run_modelmerger' params. 'config_source' is ignored
Try to use old 'run_modelmerger' params. 'Checkpoint format is forced to 'ckpt'
run_modelmerger() missing 8 required positional arguments: 'checkpoint_format', 'config_source', 'bake_in_vae', 'discard_weights', 'save_metadata', 'add_merge_recipe', 'copy_metadata_fields', and 'metadata_json'
run_modelmerger() missing 9 required positional arguments: 'custom_name', 'checkpoint_format', 'config_source', 'bake_in_vae', 'discard_weights', 'save_metadata', 'add_merge_recipe', 'copy_metadata_fields', and 'metadata_json'
All Multi-Merge process finished. 1 files.
  Error <TypeError>
```

**Comment by bbc-mc** [comment]
Hi, thanks for report!
Please try new commit to fix this problem.

**Comment by koblue** [comment]
Amazing! Works as before.
